### ISSUE TITLE
Percent BMI bug

### ISSUE THREAD

**Issue by m3stone** [mvogel78/childsds#3]
The percent BMI code appears to be bugged and is outputting a data.frame.  

See attached images:

![Capture_SDS_ERROR](https://user-images.githubusercontent.com/48774771/54722915-146ae880-4b23-11e9-9f51-d4a13dc89acb.PNG)

![Capture_SDS_ERROR_2](https://user-images.githubusercontent.com/48774771/54722970-36646b00-4b23-11e9-8ebc-ccbfdf8cf8c4.PNG)

**Comment by mvogel78** [comment]
Solved in version 0.7.4
