### ISSUE TITLE
warnings using ukwho.ref for BMI

### ISSUE THREAD

**Issue by philip-ad** [mvogel78/childsds#6]
Hi
Whenever I run the sds(.) with ref = ukwho and item ='bmi' I get a series 8 of identical warnings "In regularize.values(x, y, ties, missing(ties), na.rm = na.rm) :
  collapsing to unique 'x' values"

It does however produce a value which looks credible. 
I am not getting this message with height or weight or with other references (such as uk1990)

Any ideas? Should the results still be reliable despite the warnings

thanks and best wishes
Phil

**Comment by mvogel78** [comment]
Hi Phil,
thanks for your message. The warnings are because of a duplicated line in
the references. Nothing to worry about, the calculations are correct.
However, I will fix it in the next version.

Regards
Mandy

Am Fr., 8. Jan. 2021 um 17:52 Uhr schrieb philip-ad <
notifications@github.com>:

**Comment by philip-ad** [comment]
OK thanks Mandy and thanks for thanks for the great package. Has been really useful.

best wishes

Phil
